### ISSUE TITLE
config.AddHostKey is ignored by server (and new key generated)

### ISSUE THREAD

**Issue by andig** [gliderlabs/ssh#144]
I'm coming from go/ssh and am trying to understand how to get started. I have an ssh config with host key added:

	config.AddHostKey(signer)

Server is configured to use the config:

	server := ssh.Server{
		ServerConfigCallback: func(ctx ssh.Context) *gossh.ServerConfig {
			return config
		} ...
	}

	for _, addr := range addrs {
		hostport := net.JoinHostPort(addr, "22")
		listener, err := net.Listen("tcp", hostport)
		if err != nil {
			log.Fatal(err)
		}

		fmt.Printf("listening on %s\n", hostport)
		go server.Serve(listener)
	}

Yet, when connecting, I'm getting `REMOTE HOST IDENTIFICATION HAS CHANGED` although the key didn't change. Am I using the wrong method to add the host key?

**Comment by andig** [comment]
Update: while this doesn't work:

	config := gossh.ServerConfig{}
	config.AddHostKey(signer)

	server := ssh.Server{
		Addr: "localhost:2222",
		ServerConfigCallback: func(ctx ssh.Context) *gossh.ServerConfig {
			return &config
		},
	}

	log.Fatal(server.ListenAndServe())

this does:

	server := ssh.Server{
		Addr: "localhost:2222",
	}

	server.AddHostKey(signer)

	log.Fatal(server.ListenAndServe())

It seems, that the host keys from the server config object are ignored?

**Comment by belak** [comment]
Yes, the host keys from the ServerConfig are ignored because we don't actually have access to them.

https://pkg.go.dev/golang.org/x/crypto/ssh#ServerConfig

The ServerConfig has AddHostKey, but it adds the keys to c.hostKeys which we can't see. This unfortunately means there's no way to tell if we need to generate a host key, so we currently require using our own server.AddHostKey.

If you have any suggestions on how to make this better, I'd love to hear them.

**Comment by andig** [comment]
Understood- it was just not obvious to me, thank you!
